export function initializeBoreal(root, contactUrl) {
const cleanups=[];function listen(el,type,handler,options){el.addEventListener(type,handler,options);cleanups.push(()=>el.removeEventListener(type,handler,options))}
const q=s=>root.querySelector(s),sc=q('#ns-scroll'),story=q('#ns-story'),pin=q('#ns-pin');const state={chapter:-1,motion:!globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches,approved:false,history:'',videoURL:'',imageURL:''};const reduce=globalThis.matchMedia?matchMedia('(prefers-reduced-motion: reduce)'):null;const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stages=['Entrada','Produção','Edição','Aprovação','Para Postar','Concluído'];const stageColors=['#a8a2b8','#6a9bff','#b980fc','#edac56','#62c7dc','#75c99d'];
const headings=[['A ideia chegou.<br><strong>O flow começou.</strong>','Um pedido vira card com briefing, responsável e prazo. O trabalho começa organizado.'],['Cada job com alguém.<br><strong>Cada pessoa com contexto.</strong>','O profissional é escalado e recebe o aviso. Menos mensagens para descobrir quem faz o quê.'],['Foco na criação.<br><strong>O andamento fica visível.</strong>','O card avança para edição e o solicitante é avisado. A equipe pode se concentrar no trabalho.'],['Pronto para revisar.<br><strong>Sem caçar a última versão.</strong>','A entrega chega à aprovação. Quem precisa revisar recebe um aviso para conferir o material.'],['Aprovado.<br><strong>Falta colocar no mundo.</strong>','A decisão fica registrada. O job entra em Para Postar, com o próximo passo claro.'],['Job concluído.<br><strong>Espaço para a próxima ideia.</strong>','O trabalho chega ao fim e a equipe recebe a atualização. Um flow inteiro, organizado no NuFlow.']];
const messages=['Sua demanda foi recebida: Filme de lançamento (VOP-26-1042).','Você foi escalado para Filme de lançamento (VOP-26-1042). Confirme sua participação.','Filme de lançamento (VOP-26-1042) entrou em edição. Avisamos quando ficar pronto.','O seu vídeo está pronto para revisão. Assista e aprove Filme de lançamento.','O cliente aprovou Filme de lançamento. O job está pronto para publicação.','Filme de lançamento foi publicado. Mais uma entrega concluída!'];
function scene(){return `<div class="nb-board" id="nb-board">${stages.map((s,i)=>`<div class="nb-col" style="--step:${stageColors[i]}"><b>${s}</b><div class="nb-ghost"></div></div>`).join('')}<button class="nb-job" data-open="card"><small>VOP-26-1042 · NORMAL</small><strong>Filme de lançamento</strong><em id="nb-card-stage">Entrada</em></button></div><div class="nb-toast" id="nb-toast"><i data-lucide="message-circle" aria-hidden="true"></i><div><strong>WHATSAPP · NUFlow</strong><span id="nb-message"></span><small>Notificação demonstrativa · Nenhum envio real</small></div></div>`}
function confetti(){if(!state.motion||reduce?.matches)return;const host=q('.ns-window');for(let i=0;i<42;i++){const p=document.createElement('span');p.className='nb-confetti';p.setAttribute('aria-hidden','true');p.style.background=stageColors[i%6];host.appendChild(p);const a=(i/42)*Math.PI*2,dist=100+(i%7)*24;if(p.animate){const animation=p.animate([{transform:'translate(0,0) rotate(0)',opacity:1},{transform:`translate(${Math.cos(a)*dist}px,${Math.sin(a)*dist-50}px) rotate(${i*27}deg)`,opacity:1,offset:.6},{transform:`translate(${Math.cos(a)*dist*1.2}px,${Math.sin(a)*dist+130}px) rotate(${i*40}deg)`,opacity:0}],{duration:1200+(i%5)*90,easing:'cubic-bezier(.2,.7,.3,1)'});animation.onfinish=()=>p.remove()}else p.remove()}}
function showChapter(n){if(n===state.chapter)return;state.chapter=n;q('#ns-title').innerHTML=headings[n][0];q('#ns-description').textContent=headings[n][1];q('#ns-location').textContent='Audiovisual / '+stages[n];if(!q('#nb-board'))q('#ns-scene').innerHTML=scene();root.style.setProperty('--stage',n);root.style.setProperty('--mobile-stage',n%3);root.style.setProperty('--mobile-row',Math.floor(n/3));q('#nb-card-stage').textContent=stages[n];q('#nb-message').textContent=messages[n];root.querySelectorAll('[data-chapter]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.chapter===n)));animate(q('#nb-toast'));if(n===5)confetti();}

function animate(el){if(state.motion&&!reduce?.matches&&el?.animate)el.animate([{transform:'translateY(16px)',opacity:.4},{transform:'translateY(0)',opacity:1}],{duration:500,easing:'ease-out'})}
function start(){return story.getBoundingClientRect().top-sc.getBoundingClientRect().top+sc.scrollTop}function range(){return Math.max(1,story.offsetHeight-pin.offsetHeight)}
function update(){root.style.setProperty('--ns-h',Math.max(520,sc.clientHeight-8)+'px');const p=clamp((sc.scrollTop-start())/range(),0,1);root.style.setProperty('--ns-progress',p);root.style.setProperty('--ns-slide',state.motion&&!reduce?.matches?(state.chapter===1?clamp(p*6-1,0,1):0):0);showChapter(Math.min(5,Math.floor(p*6)));const dashboard=q('.ns-dashboard');if(dashboard){let r=dashboard.getBoundingClientRect(),v=sc.getBoundingClientRect();dashboard.style.setProperty('--ns-reveal',state.motion&&!reduce?.matches?clamp((v.bottom-r.top)/200,0,1):1)}}
let frame=0;listen(sc,'scroll',()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;update()})},{passive:true});function chapter(n){sc.scrollTo({top:start()+range()*(n+.08)/6,behavior:state.motion&&!reduce?.matches?'smooth':'auto'});showChapter(n)}function jump(id){let el=q('#'+id);sc.scrollTo({top:el.getBoundingClientRect().top-sc.getBoundingClientRect().top+sc.scrollTop,behavior:state.motion&&!reduce?.matches?'smooth':'auto'})}
function open(kind,plan){const titles={card:'Filme de lançamento',event:'Captação · Filme de lançamento',ai:'Por que essa demanda pede atenção?',notifications:'Avisos que acompanham o trabalho',performance:'Performance por videomaker',history:'Sua história, com suas palavras',demo:'Conversar com especialista',plan:'Interesse no plano '+(plan||'')};q('#ns-dialog-title').textContent=titles[kind]||'NuFlow';const body={card:'<p>VOP-26-1042 · Em produção</p><div class="ns-field"><small>Briefing</small>Apresentar a nova linha em um filme de 30 segundos.</div><p><b>Responsável:</b> Rafael<br><b>Captação:</b> 9 set · 09:00<br><b>Prazo:</b> 11 set</p><p>O card reúne briefing, equipe, links de produção, documentos, checklist e comentários.</p><button data-jump="nb-agenda" data-dismiss>Ver na agenda →</button>',event:'<p><b>9 de setembro · 09:00 — 10:00</b></p><p>Estúdio · Rafael<br>Gravação do filme de lançamento da nova linha.</p><button data-open="card">Abrir demanda relacionada →</button>',ai:'<p>Exemplo ilustrativo, sem execução de IA nesta página.</p><p><b>Dados considerados:</b> 4 demandas ativas com Rafael; 1 filme atrasado há 2 dias.</p><p><b>Recomendação:</b> conferir a urgência, alinhar um prazo viável e avaliar redistribuição. Nenhum prazo ou responsável é alterado nesta demonstração.</p>',notifications:'<p><b>Atribuição:</b> “Você foi escalado para Filme de lançamento.”</p><p><b>Edição:</b> “Filme de lançamento entrou em edição.”</p><p><b>Revisão:</b> aviso para conferir a entrega.</p><p class="ns-admin-note">Os destinatários dependem do evento e da configuração da empresa. Falhas de envio não equivalem a mensagem entregue.</p>',performance:'<p>Últimos 30 dias · Dados ilustrativos.</p><p><b>Rafael:</b> 5 concluídas, 4 ativas, 1 atrasada.<br><b>Marina:</b> 4 concluídas, 3 ativas, 1 atrasada.<br><b>Bruno:</b> 3 concluídas, 1 ativa, 0 atrasadas.</p><p>Custos demonstrativos: R$ 2.500, R$ 2.000 e R$ 1.500, respectivamente. Volume não mede sozinho qualidade ou complexidade.</p>',history:`<form id="ns-history-form"><label for="ns-history-text">Conte sua trajetória e por que criou o NuFlow</label><textarea id="ns-history-text" required>${escape(state.history)}</textarea><button class="ns-primary" type="submit" style="margin-top:15px">Aplicar ao protótipo</button></form>`};q('#ns-dialog-body').innerHTML=body[kind]|| (contactUrl ? `<p>Converse com nossa equipe sobre o plano de R$ 59/mês e confirme os recursos e limites para sua operação.</p><a class="ns-login" href="${escape(contactUrl)}" target="_blank" rel="noopener noreferrer">Conversar pelo WhatsApp ↗</a>` : '<p>O atendimento comercial está sendo preparado. Você já tem uma conta? Entre para acessar sua empresa.</p><a class="ns-login" href="/login">Acessar sistema →</a>');if(!q('#ns-dialog').open)q('#ns-dialog').showModal()}
listen(root,'click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-dismiss'))q('#ns-dialog').close();if(b.dataset.chapter!==undefined)chapter(+b.dataset.chapter);if(b.dataset.jump)jump(b.dataset.jump);if(b.id==='ns-next')chapter((state.chapter+1)%6);if(b.id==='ns-motion'){state.motion=!state.motion;root.dataset.still=String(!state.motion);b.setAttribute('aria-checked',String(state.motion));b.textContent=state.motion?'Movimento ligado':'Movimento desligado';update()}if(b.dataset.open)open(b.dataset.open);if(b.dataset.plan)open('plan',b.dataset.plan);if(b.id==='ns-close')q('#ns-dialog').close();if(b.hasAttribute('data-approve')){state.approved=!state.approved;showChapter(5)}});
listen(root,'submit',e=>{e.preventDefault();if(e.target.id==='ns-history-form'){state.history=q('#ns-history-text').value.trim();if(!state.history)return;q('#ns-founder-copy').textContent=state.history;q('#ns-dialog').close()}if(e.target.id==='ns-lead')q('#ns-dialog-body').innerHTML='<p role="status">✓ Interesse registrado apenas na demonstração. Nenhum dado foi enviado.</p>'});
listen(root,'input',e=>{if(e.target.id==='ns-value0'||e.target.id==='ns-value1'){const n=e.target.id.slice(-1),v=e.target.value;q('#ns-price-'+n).textContent=v!==''&&Number(v)>=0?Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}):'A definir'}});
listen(root,'change',e=>{const f=e.target.files?.[0];if(!f)return;if(e.target.id==='ns-video'){if(!['video/mp4','video/webm'].includes(f.type)){q('#ns-media-status').textContent='Selecione MP4 ou WebM.';return}if(state.videoURL)URL.revokeObjectURL(state.videoURL);state.videoURL=URL.createObjectURL(f);let video=document.createElement('video');video.controls=true;video.src=state.videoURL;video.playsInline=true;const old=q('#ns-video-slot video');if(old)old.remove();q('#ns-video-slot').prepend(video);q('#ns-media-status').textContent='Vídeo carregado localmente, sem envio.'}if(e.target.id==='ns-proof-file'){if(!['image/png','image/jpeg'].includes(f.type)){q('#ns-media-status').textContent='Selecione PNG ou JPEG.';return}if(state.imageURL)URL.revokeObjectURL(state.imageURL);state.imageURL=URL.createObjectURL(f);let img=document.createElement('img');img.src=state.imageURL;img.alt='Depoimento fornecido para prévia local';q('#ns-proof-image').replaceChildren(img);q('#ns-media-status').textContent='Captura carregada localmente, sem envio.'}});

const jobNames=['Carrossel · Nova linha','Filme de apresentação','Campanha de setembro'];const accepted=new Set();
function renderJobs(){q('#nb-jobs').innerHTML=jobNames.map((name,i)=>`<article class="nb-approval"><small>VOP-26-${6105+i} · ${i===1?'Audiovisual':'Growth'}</small><h3>${name}</h3><p>Briefing, objetivo e referências reunidos para analisar a entrada.</p><button data-job="${i}" ${accepted.has(i)?'disabled':''}>${accepted.has(i)?'✓ Aprovado como job':'Aprovar como job →'}</button></article>`).join('');q('#nb-count').textContent=String(3-accepted.size)}
function replayJobs(){root.querySelectorAll('.nb-approval').forEach((el,i)=>{if(state.motion&&!reduce?.matches&&el.animate)el.animate([{transform:'translateY(60px) scale(.92)',opacity:0},{transform:'translateY(0) scale(1)',opacity:1}],{duration:650,delay:i*200,fill:'backwards',easing:'cubic-bezier(.2,.8,.2,1)'})})}
listen(root,'click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='nb-schedule'){q('#nb-appointment').innerHTML='<button class="ns-event" data-open="event"><small>09:00 · Captação</small>Filme de lançamento<br>Rafael</button>';q('#nb-calendar-toast').innerHTML='<div class="nb-toast"><div><strong>WHATSAPP · AGENDAMENTO</strong>Captação de Filme de lançamento agendada para 9 set, às 09:00.<small>Notificação demonstrativa</small></div></div>';animate(q('#nb-appointment'));animate(q('#nb-calendar-toast'));b.textContent='Rever agendamento ↺'}if(b.id==='nb-replay')replayJobs();if(b.dataset.job!==undefined){accepted.add(+b.dataset.job);renderJobs()}});

showChapter(0);renderJobs();if(globalThis.IntersectionObserver){const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){replayJobs();obs.unobserve(e.target)}})},{root:sc,threshold:.3});obs.observe(q("#nb-jobs"));cleanups.push(()=>obs.disconnect())}if(globalThis.ResizeObserver){const resize=new ResizeObserver(update);resize.observe(sc);cleanups.push(()=>resize.disconnect())}

root.dataset.still=String(!state.motion); q("#ns-motion").setAttribute("aria-checked",String(state.motion));q("#ns-motion").textContent=state.motion?"Movimento ligado":"Movimento desligado";update();
return ()=>{cleanups.forEach(fn=>fn());cancelAnimationFrame(frame);if(state.videoURL)URL.revokeObjectURL(state.videoURL);if(state.imageURL)URL.revokeObjectURL(state.imageURL)};
}
