export function initializeBoreal(root, contactUrl) {
const cleanups=[];function listen(el,type,handler,options){el.addEventListener(type,handler,options);cleanups.push(()=>el.removeEventListener(type,handler,options))}
const q=s=>root.querySelector(s),sc=q('#ns-scroll'),story=q('#ns-story'),pin=q('#ns-pin');const state={chapter:-1,motion:!globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches,approved:false,history:'',videoURL:'',imageURL:''};const reduce=globalThis.matchMedia?matchMedia('(prefers-reduced-motion: reduce)'):null;const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stages=['Entrada','Produção','Edição','Aprovação','Para Postar','Concluído'];const stageColors=['#a8a2b8','#6a9bff','#b980fc','#edac56','#62c7dc','#75c99d'];
const headings=[['A ideia chegou.<br><strong>O flow começou.</strong>','Um pedido vira card com briefing, responsável e prazo. O trabalho começa organizado.'],['Cada job com alguém.<br><strong>Cada pessoa com contexto.</strong>','O profissional é escalado e recebe o aviso. Menos mensagens para descobrir quem faz o quê.'],['Foco na criação.<br><strong>O andamento fica visível.</strong>','O card avança para edição e o solicitante é avisado. A equipe pode se concentrar no trabalho.'],['Pronto para revisar.<br><strong>Sem caçar a última versão.</strong>','A entrega chega à aprovação. Quem precisa revisar recebe um aviso para conferir o material.'],['Aprovado.<br><strong>Falta colocar no mundo.</strong>','A decisão fica registrada. O job entra em Para Postar, com o próximo passo claro.'],['Job concluído.<br><strong>Espaço para a próxima ideia.</strong>','O trabalho chega ao fim e a equipe recebe a atualização. Um flow inteiro, organizado no NuFlow.']];
const messages=['Sua demanda foi recebida: Filme de lançamento (VOP-26-1042).','Você foi escalado para Filme de lançamento (VOP-26-1042). Confirme sua participação.','Filme de lançamento (VOP-26-1042) entrou em edição. Avisamos quando ficar pronto.','O seu vídeo está pronto para revisão. Assista e aprove Filme de lançamento.','O cliente aprovou Filme de lançamento. O job está pronto para publicação.','Filme de lançamento foi publicado. Mais uma entrega concluída!'];
function scene(){return `<div class="nb-board" id="nb-board">${stages.map((s,i)=>`<div class="nb-col" style="--step:${stageColors[i]}"><b>${s}</b><div class="nb-ghost"></div></div>`).join('')}<button class="nb-job" data-open="card"><small>VOP-26-1042 · NORMAL</small><strong>Filme de lançamento</strong><em id="nb-card-stage">Entrada</em></button></div><div class="nb-toast" id="nb-toast"><i data-lucide="message-circle" aria-hidden="true"></i><div><strong>WHATSAPP · NUFlow</strong><span id="nb-message"></span><small>Notificação demonstrativa · Nenhum envio real</small></div></div>`}
function confetti(){if(!state.motion||reduce?.matches)return;const host=q('.ns-window');for(let i=0;i<42;i++){const p=document.createElement('span');p.className='nb-confetti';p.setAttribute('aria-hidden','true');p.style.background=stageColors[i%6];host.appendChild(p);const a=(i/42)*Math.PI*2,dist=100+(i%7)*24;if(p.animate){const animation=p.animate([{transform:'translate(0,0) rotate(0)',opacity:1},{transform:`translate(${Math.cos(a)*dist}px,${Math.sin(a)*dist-50}px) rotate(${i*27}deg)`,opacity:1,offset:.6},{transform:`translate(${Math.cos(a)*dist*1.2}px,${Math.sin(a)*dist+130}px) rotate(${i*40}deg)`,opacity:0}],{duration:1200+(i%5)*90,easing:'cubic-bezier(.2,.7,.3,1)'});animation.onfinish=()=>p.remove()}else p.remove()}}
function showChapter(n){if(n===state.chapter)return;state.chapter=n;q('#ns-title').innerHTML=headings[n][0];q('#ns-description').textContent=headings[n][1];q('#ns-location').textContent='Audiovisual / '+stages[n];if(!q('#nb-board'))q('#ns-scene').innerHTML=scene();root.style.setProperty('--stage',n);root.style.setProperty('--mobile-stage',n%3);root.style.setProperty('--mobile-row',Math.floor(n/3));q('#nb-card-stage').textContent=stages[n];q('#nb-message').textContent=messages[n];root.querySelectorAll('[data-chapter]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.chapter===n)));animate(q('#nb-toast'));if(n===5)confetti();}

function animate(el){if(state.motion&&!reduce?.matches&&el?.animate)el.animate([{transform:'translateY(16px)',opacity:.4},{transform:'translateY(0)',opacity:1}],{duration:500,easing:'ease-out'})}
function start(){return story.getBoundingClientRect().top+globalThis.scrollY-q('.ns-header').offsetHeight}function range(){return Math.max(1,story.offsetHeight-pin.offsetHeight)}
function update(){root.style.setProperty('--header-h',q('.ns-header').offsetHeight+'px');root.style.setProperty('--ns-h',Math.max(400,globalThis.innerHeight-q('.ns-header').offsetHeight)+'px');const p=clamp((globalThis.scrollY-start())/range(),0,1);root.style.setProperty('--ns-progress',p);root.style.setProperty('--ns-slide',state.motion&&!reduce?.matches?(state.chapter===1?clamp(p*6-1,0,1):0):0);showChapter(Math.min(5,Math.floor(p*6)));const dashboard=q('.ns-dashboard');if(dashboard){let r=dashboard.getBoundingClientRect(),v={top:0,bottom:globalThis.innerHeight};dashboard.style.setProperty('--ns-reveal',state.motion&&!reduce?.matches?clamp((v.bottom-r.top)/200,0,1):1)}}
let frame=0;listen(globalThis,'scroll',()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;update()})},{passive:true});function chapter(n){globalThis.scrollTo({top:start()+range()*(n+.08)/6,behavior:state.motion&&!reduce?.matches?'smooth':'auto'});showChapter(n)}function jump(id){let el=q('#'+id);globalThis.scrollTo({top:el.getBoundingClientRect().top+globalThis.scrollY-q('.ns-header').offsetHeight,behavior:state.motion&&!reduce?.matches?'smooth':'auto'})}
function open(kind,plan){const titles={card:'Filme de lançamento',event:'Captação · Filme de lançamento',ai:'Por que essa demanda pede atenção?',notifications:'Avisos que acompanham o trabalho',performance:'Performance por videomaker',history:'Sua história, com suas palavras',demo:'Conversar com especialista',plan:'Interesse no plano '+(plan||'')};q('#ns-dialog-title').textContent=titles[kind]||'NuFlow';const body={card:'<p>VOP-26-1042 · Em produção</p><div class="ns-field"><small>Briefing</small>Apresentar a nova linha em um filme de 30 segundos.</div><p><b>Responsável:</b> Rafael<br><b>Captação:</b> 9 set · 09:00<br><b>Prazo:</b> 11 set</p><p>O card reúne briefing, equipe, links de produção, documentos, checklist e comentários.</p><button data-jump="nb-agenda" data-dismiss>Ver na agenda →</button>',event:'<p><b>9 de setembro · 09:00 — 10:00</b></p><p>Estúdio · Rafael<br>Gravação do filme de lançamento da nova linha.</p><button data-open="card">Abrir demanda relacionada →</button>',ai:'<p>Exemplo ilustrativo, sem execução de IA nesta página.</p><p><b>Dados considerados:</b> 4 demandas ativas com Rafael; 1 filme atrasado há 2 dias.</p><p><b>Recomendação:</b> conferir a urgência, alinhar um prazo viável e avaliar redistribuição. Nenhum prazo ou responsável é alterado nesta demonstração.</p>',notifications:'<p><b>Atribuição:</b> “Você foi escalado para Filme de lançamento.”</p><p><b>Edição:</b> “Filme de lançamento entrou em edição.”</p><p><b>Revisão:</b> aviso para conferir a entrega.</p><p class="ns-admin-note">Os destinatários dependem do evento e da configuração da empresa. Falhas de envio não equivalem a mensagem entregue.</p>',performance:'<p>Últimos 30 dias · Dados ilustrativos.</p><p><b>Rafael:</b> 5 concluídas, 4 ativas, 1 atrasada.<br><b>Marina:</b> 4 concluídas, 3 ativas, 1 atrasada.<br><b>Bruno:</b> 3 concluídas, 1 ativa, 0 atrasadas.</p><p>Custos demonstrativos: R$ 2.500, R$ 2.000 e R$ 1.500, respectivamente. Volume não mede sozinho qualidade ou complexidade.</p>',history:`<form id="ns-history-form"><label for="ns-history-text">Conte sua trajetória e por que criou o NuFlow</label><textarea id="ns-history-text" required>${escape(state.history)}</textarea><button class="ns-primary" type="submit" style="margin-top:15px">Aplicar ao protótipo</button></form>`};q('#ns-dialog-body').innerHTML=body[kind]|| (contactUrl ? `<p>Fale com a equipe do NuFlow sobre recursos, limites e condições para a sua operação.</p><a class="ns-login" href="${escape(contactUrl)}" target="_blank" rel="noopener noreferrer">Conversar pelo WhatsApp ↗</a><p>Prefere que a gente chame você? <a href="/comecar">Deixe seu contato</a>.</p>` : '<p>Conte um pouco sobre sua operação e a equipe do NuFlow fala com você pelo e-mail ou WhatsApp.</p><a class="ns-login" href="/comecar">Deixar meu contato →</a><p>Já tem conta? <a href="/login">Entrar</a>.</p>');if(!q('#ns-dialog').open)q('#ns-dialog').showModal()}
listen(root,'click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-dismiss'))q('#ns-dialog').close();if(b.dataset.chapter!==undefined)chapter(+b.dataset.chapter);if(b.dataset.jump)jump(b.dataset.jump);if(b.id==='ns-next')chapter((state.chapter+1)%6);if(b.id==='ns-motion'){state.motion=!state.motion;root.dataset.still=String(!state.motion);b.setAttribute('aria-checked',String(state.motion));b.textContent=state.motion?'Movimento ligado':'Movimento desligado';update()}if(b.dataset.open)open(b.dataset.open);if(b.dataset.plan)open('plan',b.dataset.plan);if(b.id==='ns-close')q('#ns-dialog').close();if(b.hasAttribute('data-approve')){state.approved=!state.approved;showChapter(5)}});
listen(root,'submit',e=>{e.preventDefault();if(e.target.id==='ns-history-form'){state.history=q('#ns-history-text').value.trim();if(!state.history)return;q('#ns-founder-copy').textContent=state.history;q('#ns-dialog').close()}if(e.target.id==='ns-lead')q('#ns-dialog-body').innerHTML='<p role="status">✓ Interesse registrado apenas na demonstração. Nenhum dado foi enviado.</p>'});
listen(root,'input',e=>{if(e.target.id==='ns-value0'||e.target.id==='ns-value1'){const n=e.target.id.slice(-1),v=e.target.value;q('#ns-price-'+n).textContent=v!==''&&Number(v)>=0?Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}):'A definir'}});
listen(root,'change',e=>{const f=e.target.files?.[0];if(!f)return;if(e.target.id==='ns-video'){if(!['video/mp4','video/webm'].includes(f.type)){q('#ns-media-status').textContent='Selecione MP4 ou WebM.';return}if(state.videoURL)URL.revokeObjectURL(state.videoURL);state.videoURL=URL.createObjectURL(f);let video=document.createElement('video');video.controls=true;video.src=state.videoURL;video.playsInline=true;const old=q('#ns-video-slot video');if(old)old.remove();q('#ns-video-slot').prepend(video);q('#ns-media-status').textContent='Vídeo carregado localmente, sem envio.'}if(e.target.id==='ns-proof-file'){if(!['image/png','image/jpeg'].includes(f.type)){q('#ns-media-status').textContent='Selecione PNG ou JPEG.';return}if(state.imageURL)URL.revokeObjectURL(state.imageURL);state.imageURL=URL.createObjectURL(f);let img=document.createElement('img');img.src=state.imageURL;img.alt='Depoimento fornecido para prévia local';q('#ns-proof-image').replaceChildren(img);q('#ns-media-status').textContent='Captura carregada localmente, sem envio.'}});

const jobNames=['Carrossel · Nova linha','Filme de apresentação','Campanha de setembro'];const accepted=new Set();
function renderJobs(){q('#nb-jobs').innerHTML=jobNames.map((name,i)=>`<article class="nb-approval"><small>VOP-26-${6105+i} · ${i===1?'Audiovisual':'Growth'}</small><h3>${name}</h3><p>Briefing, objetivo e referências reunidos para analisar a entrada.</p><button data-job="${i}" ${accepted.has(i)?'disabled':''}>${accepted.has(i)?'✓ Aprovado como job':'Aprovar como job →'}</button></article>`).join('');q('#nb-count').textContent=String(3-accepted.size)}
function replayJobs(){root.querySelectorAll('.nb-approval').forEach((el,i)=>{if(state.motion&&!reduce?.matches&&el.animate)el.animate([{transform:'translateY(60px) scale(.92)',opacity:0},{transform:'translateY(0) scale(1)',opacity:1}],{duration:650,delay:i*200,fill:'backwards',easing:'cubic-bezier(.2,.8,.2,1)'})})}
listen(root,'click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='nb-schedule'){q('#nb-appointment').innerHTML='<button class="ns-event" data-open="event"><small>09:00 · Captação</small>Filme de lançamento<br>Rafael</button>';q('#nb-calendar-toast').innerHTML='<div class="nb-toast"><div><strong>WHATSAPP · AGENDAMENTO</strong>Captação de Filme de lançamento agendada para 9 set, às 09:00.<small>Notificação demonstrativa</small></div></div>';animate(q('#nb-appointment'));animate(q('#nb-calendar-toast'));b.textContent='Rever agendamento ↺'}if(b.id==='nb-replay')replayJobs();if(b.dataset.job!==undefined){accepted.add(+b.dataset.job);renderJobs()}});

showChapter(0);renderJobs();if(globalThis.IntersectionObserver){const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){replayJobs();obs.unobserve(e.target)}})},{root:null,threshold:.3});obs.observe(q("#nb-jobs"));cleanups.push(()=>obs.disconnect())}if(globalThis.ResizeObserver){const resize=new ResizeObserver(update);resize.observe(sc);listen(globalThis,'resize',update);cleanups.push(()=>resize.disconnect())}

root.dataset.still=String(!state.motion); q("#ns-motion").setAttribute("aria-checked",String(state.motion));q("#ns-motion").textContent=state.motion?"Movimento ligado":"Movimento desligado";update();
const timelines=new Map();
function clearTimeline(key){(timelines.get(key)||[]).forEach(clearTimeout);timelines.set(key,[])}
function later(key,fn,ms){const id=setTimeout(fn,ms);timelines.get(key).push(id)}
function visible(el){const r=el.getBoundingClientRect(),v={top:0,bottom:globalThis.innerHeight};return r.bottom>v.top+80&&r.top<v.bottom}
function runSequence(key,steps){clearTimeline(key);steps.forEach(([delay,fn])=>{if(!state.motion||reduce?.matches)fn();else later(key,fn,delay)})}
function scheduleDemo(){runSequence('agenda',[[0,()=>{q('#nb-appointment').innerHTML='<small>Reservando horário…</small>';q('#nb-calendar-toast').innerHTML='';q('#nb-schedule').textContent='Rever agendamento ↺'}],[700,()=>{q('#nb-appointment').innerHTML='<button class="ns-event" data-open="event"><small>09:00 · Captação</small>Filme de lançamento<br>Rafael · Confirmado ✓</button>';animate(q('#nb-appointment'))}],[1700,()=>{q('#nb-calendar-toast').innerHTML='<div class="nf-message"><strong>WhatsApp · Captação confirmada</strong><p>Rafael, sua gravação está marcada para 9 set, às 09:00. O briefing está no card.</p></div>';animate(q('#nb-calendar-toast'))}],[3400,()=>{q('#nb-calendar-toast').innerHTML='<div class="nf-message"><strong>WhatsApp · Lembrete de agenda</strong><p>Sua captação começa em 1 hora. Confira o local e os detalhes no NuFlow.</p><small>Demonstração de lembrete</small></div>';animate(q('#nb-calendar-toast'))}]])}
const examples=['Carrossel · Nova coleção','Email · Boas-vindas','Landing page · Lançamento','Post · Bastidores','Apresentação comercial','Campanha · Primavera'];
function approveDemo(){const offset=Math.floor(Math.random()*examples.length);jobNames.splice(0,3,...[0,1,2].map(i=>examples[(offset+i)%examples.length]));accepted.clear();renderJobs();replayJobs();runSequence('jobs',[0,1,2].map(i=>[1200+i*1200,()=>{accepted.add(i);const card=q('#nb-jobs').children[i];card.classList.add('nf-approved');const b=card.querySelector('button');b.textContent='✓ Aprovado como job';b.disabled=true;q('#nb-count').textContent=String(3-accepted.size);animate(card)}]))}
const noticeExamples=[['Novo job para você','Você foi escalado para o filme de lançamento. Briefing, responsável e prazo estão no card.'],['Sua agenda te chama','Captação amanhã, às 09:00. Confira o local antes de sair.'],['O flow avançou','O filme entrou em aprovação. A próxima decisão já tem responsável.']];
function messagesDemo(){q('#nf-messages').innerHTML='';runSequence('messages',noticeExamples.map(([title,copy],i)=>[i*1200,()=>{const item=document.createElement('div');item.className='nf-message';item.innerHTML=`<strong>WhatsApp · ${title}</strong><p>${copy}</p>`;q('#nf-messages').appendChild(item);animate(item)}]))}
function performanceDemo(){root.querySelectorAll('.ns-bar>span').forEach(el=>{if(state.motion&&!reduce?.matches&&el.animate)el.animate([{transform:'scaleX(0)',transformOrigin:'left'},{transform:'scaleX(1)',transformOrigin:'left'}],{duration:1600,easing:'ease-out'})});runSequence('performance',[[0,()=>{q('#nf-performance-alert').dataset.free='false';q('#nf-performance-alert').textContent='Atenção à carga · Rafael está com 4 jobs ativos e 1 atrasado.';animate(q('#nf-performance-alert'))}],[2800,()=>{q('#nf-performance-alert').dataset.free='true';q('#nf-performance-alert').textContent='Disponibilidade · Bruno tem 1 job ativo. Avalie redistribuir a próxima demanda.';animate(q('#nf-performance-alert'))}]])}
listen(root,'click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='nb-schedule')scheduleDemo();if(b.id==='nb-replay')approveDemo();if(b.id==='ns-motion'&&!state.motion){timelines.forEach((_,k)=>clearTimeline(k));root.querySelectorAll('*').forEach(el=>el.getAnimations?.().forEach(a=>a.finish()))}});
const sections=[['#nb-agenda',scheduleDemo],['#nb-review',approveDemo],['#nb-focus',messagesDemo],['#ns-performance',performanceDemo]];
if(globalThis.IntersectionObserver){const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)sections.find(([selector])=>q(selector)===e.target)?.[1]();else {const key={'nb-agenda':'agenda','nb-review':'jobs','nb-focus':'messages','ns-performance':'performance'}[e.target.id];clearTimeline(key)}})},{root:null,threshold:.35});sections.forEach(([selector])=>observer.observe(q(selector)));cleanups.push(()=>observer.disconnect())}
const loop=setInterval(()=>{if(!state.motion||reduce?.matches||document.hidden)return;sections.forEach(([selector,fn])=>{if(visible(q(selector)))fn()})},10000);
cleanups.push(()=>{clearInterval(loop);timelines.forEach((_,k)=>clearTimeline(k))});

cleanups.push(startHeroMotion(root));
return ()=>{cleanups.forEach(fn=>fn());cancelAnimationFrame(frame);if(state.videoURL)URL.revokeObjectURL(state.videoURL);if(state.imageURL)URL.revokeObjectURL(state.imageURL)};
}

// ── Motion do hero ──────────────────────────────────────────────────────────
// Mensagens de WhatsApp chegam bagunçadas, viram as linhas de um card, o card
// anda pelas etapas e o conjunto vira a marca: o título do hero contado em 11 s.
// Protótipo aprovado pelo Giovani em 02/10/2026. Tudo é desenhado num palco de
// 440×500 px que escala para a largura disponível; cada quadro é calculado a
// partir do tempo, então pausar e retomar não acumula erro.
function startHeroMotion(root){
const stage=root.querySelector('#nm-stage'),outer=root.querySelector('#nm-outer'),toggle=root.querySelector('#nm-toggle'),phaseEl=root.querySelector('#nm-phase');
if(!stage||!outer)return()=>{};
const W=440,T=11,reduce=!!globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,prog=(t,s,d)=>clamp((t-s)/d);
const io=x=>x<.5?4*x*x*x:1-Math.pow(-2*x+2,3)/2,out=x=>1-Math.pow(1-x,3),back=x=>{const c1=1.6,c3=c1+1;return 1+c3*Math.pow(x-1,3)+c1*Math.pow(x-1,2)};
const el=(cls,html,parent=stage)=>{const d=document.createElement('div');d.className=cls;if(html)d.innerHTML=html;parent.appendChild(d);return d};
const put=(n,x,y,s=1,r=0,o=1)=>{n.style.transform=`translate(${x}px,${y}px) rotate(${r}deg) scale(${s})`;n.style.opacity=o;n.style.visibility=o<=.001?'hidden':'visible'};
// linha do card de destino: 0 briefing · 1 captação · 2 brutos · 3 prazo · 4 aprovação
const MSGS=[
{who:'Cliente',c:'#f5a97f',text:'Cadê o vídeo do Dr. Paulo?',x:18,y:54,r:-4,row:3},
{who:'Gestão',c:'#a6e3a1',text:'Quem grava amanhã às 9h?',x:215,y:78,r:5,row:1},
{who:'Rafael',c:'#89b4fa',audio:'0:47',x:34,y:140,r:3,row:1},
{who:'Ana · edição',c:'#cba6f7',text:'Manda o link dos brutos de novo?',x:222,y:168,r:-6,row:2},
{who:'Cliente',c:'#f5a97f',text:'O prazo não era ontem?',x:14,y:236,r:-3,row:3},
{who:'Ana · edição',c:'#cba6f7',text:'Qual é a final? v3 ou v3_final?',x:196,y:266,r:4,row:4},
{who:'Gestão',c:'#a6e3a1',text:'Alguém aprovou?',x:42,y:334,r:6,row:4},
{who:'Atendimento',c:'#f9e2af',text:'O briefing tá no e-mail, acho',x:214,y:352,r:-5,row:0},
{who:'Ana · edição',c:'#cba6f7',text:'Tô sem os brutos',x:120,y:420,r:2,row:2}];
const clock=['09:12','09:14','09:15','09:21','09:22','09:30','09:31','09:33','09:40'];
const bubbles=MSGS.map((m,i)=>el('nm-bubble',`<span class="nm-who" style="color:${m.c}">${m.who}</span>`+(m.audio?`<span class="nm-audio"><span class="nm-play"></span><span class="nm-wave"></span><span>${m.audio}</span></span>`:m.text)+`<span class="nm-meta">${clock[i]}<i>✓✓</i></span>`));
const unread=el('nm-unread','<b>0</b> não lidas'),countEl=unread.querySelector('b');
const ROWS=[['Briefing','anexado'],['Captação','Rafael · qui 09:00'],['Brutos','no Drive'],['Prazo','sex 14:00'],['Aprovação','v3 enviada']];
const card=el('nm-card','<small>VOP-26-1042 · Audiovisual</small><h3>Filme de lançamento</h3>');
const CARD={x:50,y:90},ROW_Y0=92,ROW_H=40;
const rows=ROWS.map(([a,b],i)=>{const r=el('nm-row',`<span>${a}</span><em>${b}</em><b>✓</b>`,card);r.style.top=(ROW_Y0+i*ROW_H)+'px';return{node:r,tick:r.querySelector('b'),em:r.querySelector('em')}});
const ORG0=3.65,ORG_STEP=.13,FLY=.55,order=[7,1,2,3,8,0,4,5,6];
const flyStart=i=>ORG0+order.indexOf(i)*ORG_STEP;
const rowDone=ROWS.map((_,r)=>Math.max(...MSGS.map((m,i)=>m.row===r?flyStart(i)+FLY:0)));
const COLS=[['Entrada','#a8a2b8'],['Produção','#6a9bff'],['Edição','#b980fc'],['Aprovação','#edac56'],['Concluído','#75c99d']];
const colX=k=>8+k*86;
const cols=COLS.map(([n,c],k)=>{const d=el('nm-col',`<b>${n}</b>`);d.style.setProperty('--c',c);d.style.left=colX(k)+'px';return d});
const mini=el('nm-mini','<strong>Filme de lançamento</strong><span><i></i><em>Entrada</em></span>'),miniStage=mini.querySelector('em'),miniDot=mini.querySelector('i');
const HOP0=6.05,HOP=.68;
const TOASTS=['Rafael, você foi escalado para Filme de lançamento. Captação qui, 09:00.','Brutos recebidos. Ana começou a edição.','Versão v3 pronta. Toque para revisar e aprovar.','Aprovado pelo cliente. Entrega concluída.'];
const TOAST_T=['09:00','11:42','16:05','17:20'];
const toast=el('nm-toast','<strong><span>WhatsApp · NuFlow</span><time></time></strong><p></p>'),toastP=toast.querySelector('p'),toastTime=toast.querySelector('time');
const brand=el('nm-brand','<div>NuFlow<i>.</i></div><p>O Flow devolve.</p>'),brandP=brand.querySelector('p');
const PHASES=[['Caos',0],['Organiza',3.55],['Flui',5.45],['NuFlow',8.8]];
function render(t){
MSGS.forEach((m,i)=>{const b=bubbles[i],pop=back(prog(t,.2+i*.3,.38)),fs=flyStart(i),f=io(prog(t,fs,FLY));
if(t<fs){const shake=t>3.05?Math.sin(t*46+i)*1.6*prog(t,3.05,.4):0,float=Math.sin(t*1.7+i*1.3)*2.2;put(b,m.x+shake,m.y+float,lerp(.6,1,pop),m.r*pop,prog(t,.2+i*.3,.18))}
else{const tx=CARD.x+24,ty=CARD.y+ROW_Y0+m.row*ROW_H+6;put(b,lerp(m.x,tx,f),lerp(m.y,ty,f),lerp(1,.32,f),lerp(m.r,0,f),1-prog(f,.65,.35))}});
const up=Math.round(48*out(prog(t,.2,3))),left=MSGS.filter((_,i)=>t<flyStart(i)+FLY*.6).length;
countEl.textContent=t<ORG0?up:Math.round(up*left/MSGS.length);
put(unread,0,0,1,0,prog(t,.3,.3)*(1-prog(t,5,.25)));
const cIn=out(prog(t,3.5,.4)),cOut=io(prog(t,5.4,.55));
put(card,lerp(0,colX(0)+5-50-135,cOut),lerp(0,132-90-111,cOut),lerp(.94,1,cIn)*lerp(1,.21,cOut),0,cIn*(1-prog(t,5.6,.35)));
rows.forEach((r,i)=>{r.tick.style.transform=`scale(${back(prog(t,rowDone[i]-.05,.3))})`;r.node.style.opacity=.35+.65*prog(t,rowDone[i]-.1,.2);r.em.style.opacity=prog(t,rowDone[i]-.05,.25)});
const boardOut=prog(t,8.8,.45);
cols.forEach((c,k)=>{const a=out(prog(t,5.42+k*.06,.4));put(c,0,lerp(16,0,a),1,0,a*(1-boardOut))});
let pos=0;for(let k=1;k<COLS.length;k++)pos+=io(prog(t,HOP0+(k-1)*HOP,.42));
const k=Math.min(COLS.length-1,Math.round(pos));miniStage.textContent=COLS[k][0];miniDot.style.background=COLS[k][1];
put(mini,lerp(colX(0)+5,colX(COLS.length-1)+5,pos/(COLS.length-1)),Math.sin(Math.PI*(pos%1))*-14,1+Math.sin(Math.PI*(pos%1))*.06,0,prog(t,5.75,.25)*(1-boardOut));
const hop=Math.floor((t-HOP0-.38)/HOP);
if(hop>=0&&hop<TOASTS.length&&t<8.8){const local=(t-HOP0-.38)-hop*HOP,a=out(clamp(local/.22));toastP.textContent=TOASTS[hop];toastTime.textContent=TOAST_T[hop];put(toast,0,lerp(26,0,a),1,0,hop===TOASTS.length-1?a:a*(1-prog(local,HOP-.12,.12)))}
else if(t>=8.8)put(toast,0,0,1,0,1-boardOut);else put(toast,0,26,1,0,0);
const bIn=out(prog(t,9,.6));put(brand,0,lerp(18,0,bIn),lerp(.94,1,bIn),0,bIn*(1-prog(t,10.6,.4)));brandP.style.opacity=prog(t,9.35,.5);
if(phaseEl)phaseEl.textContent=PHASES.reduce((acc,p)=>t>=p[1]?p[0]:acc,PHASES[0][0])}
// Começa com as mensagens já na tela; quem pede menos movimento vê o card organizado, parado.
let now=reduce?5.4:2.4,playing=!reduce,visible=true,raf=0,last=null;
function frame(ts){raf=0;if(last!==null)now=(now+Math.min(.05,(ts-last)/1000))%T;last=ts;render(now);if(playing&&visible&&!document.hidden)raf=requestAnimationFrame(frame);else last=null}
function run(){if(!raf&&playing&&visible&&!document.hidden){last=null;raf=requestAnimationFrame(frame)}}
function setPlaying(v){playing=v;if(toggle){toggle.textContent=v?'Pausar animação':'Tocar animação';toggle.setAttribute('aria-pressed',String(v))}run()}
const onToggle=()=>setPlaying(!playing),onVis=()=>run();
toggle?.addEventListener('click',onToggle);document.addEventListener('visibilitychange',onVis);
const io2=globalThis.IntersectionObserver?new IntersectionObserver(e=>{visible=e[0].isIntersecting;run()},{threshold:.15}):null;io2?.observe(outer);
const fit=()=>stage.style.setProperty('--nm-s',outer.clientWidth/W);
const ro=globalThis.ResizeObserver?new ResizeObserver(fit):null;ro?.observe(outer);fit();
setPlaying(playing);render(now);
return()=>{if(raf)cancelAnimationFrame(raf);raf=0;playing=false;toggle?.removeEventListener('click',onToggle);document.removeEventListener('visibilitychange',onVis);io2?.disconnect();ro?.disconnect();stage.textContent=''}}
