"use client"
import { useState } from "react"
import Link from "next/link"
import { MailCheck } from "lucide-react"
import styles from "@/components/auth/AuthSurface.module.css"
export default function EsqueciSenhaPage(){
 const [email,setEmail]=useState("");const [loading,setLoading]=useState(false);const [sent,setSent]=useState(false);const [error,setError]=useState("")
 async function submit(e:React.FormEvent){e.preventDefault();if(loading)return;setLoading(true);setError("");try{const res=await fetch("/api/auth/esqueci-senha",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const data=await res.json();if(!res.ok||!data.ok){setError(res.status===429?"Muitas tentativas. Aguarde alguns minutos antes de tentar novamente.":"Não foi possível enviar o link. Confira o e-mail ou peça ajuda ao administrador da sua empresa.")}else setSent(true)}catch{setError("Falha de conexão. Tente novamente.")}finally{setLoading(false)}}
 return <section className={styles.panel} aria-labelledby="auth-title"><p className={styles.eyebrow}>RECUPERAR ACESSO</p>{sent?<><MailCheck className={styles.success} size={36}/><h1 id="auth-title">Confira seu e-mail.</h1><p className={styles.description}>Enviamos as instruções para {email}. O link vale por uma hora. Confira também a caixa de spam.</p></>:<><h1 id="auth-title">Vamos recuperar seu acesso.</h1><p className={styles.description}>Informe o e-mail da sua conta para receber um link e criar uma nova senha.</p><form onSubmit={submit} className={styles.form} aria-busy={loading}><div className={styles.field}><label htmlFor="email">E-mail da conta</label><input id="email" name="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@empresa.com"/></div>{error&&<p role="alert" className={styles.error}>{error}</p>}<button className={styles.primary} disabled={loading}>{loading?"Enviando…":"Enviar link de recuperação"}</button></form></>}<div className={styles.links}><Link href="/login">Voltar para entrar</Link></div></section>
}
