// All API traffic is mocked. No production credentials, database or messages.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const {SignJWT}=require('jose');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const context=await browser.newContext({viewport:{width:1440,height:960},reducedMotion:'reduce'});
 const token=await new SignJWT({id:'preview-user',sub:'preview-user',tipo:'admin',papel:'admin',organizacaoId:'preview-org',name:'Pessoa de teste'}).setProtectedHeader({alg:'HS256'}).setIssuedAt().setExpirationTime('1h').sign(new TextEncoder().encode('nuflow-local-preview-only-secret-2026'.slice(0,32)));
 await context.addCookies([{name:'authjs.session-token',value:token,url:'http://127.0.0.1:3107'}]);
 const page=await context.newPage(); const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const output=process.env.QA_OUTPUT || '/tmp/nuflow-admin-qa';fs.mkdirSync(output,{recursive:true});

 const people=[{id:'u1',nome:'Rafael Lima',email:'rafael@example.test',tipo:'editor',categoria:'interna',areas:['audiovisual'],status:'ativo',createdAt:'2026-01-01',ultimoAcesso:'2026-09-01'},{id:'u2',nome:'Marina Costa',email:'marina@example.test',tipo:'designer',categoria:'interna',areas:['growth'],status:'inativo',createdAt:'2026-01-01'}];
 let role="admin"; const mutations=[];
 await context.route('**/*',async route=>{
  const req=route.request(),url=new URL(req.url());
  if(url.hostname!=='127.0.0.1')return route.abort();
  if(!url.pathname.startsWith('/api/'))return route.continue();
  if(!['GET','HEAD'].includes(req.method()))mutations.push(url.pathname);
  const reply=data=>route.fulfill({contentType:'application/json',body:JSON.stringify(data)});
  if(url.pathname==='/api/auth/session')return reply({user:{id:'preview-user',name:'Pessoa de teste',tipo:role},expires:'2099-01-01'});
  if(url.pathname==='/api/me')return reply({id:'preview-user',nome:'Pessoa de teste',tipo:'admin',modulos:{growth:true},membership:{areas:['growth'],organizacaoId:'preview-org'},permissoes:{}});
  if(url.pathname==='/api/usuarios')return reply({usuarios:people,editores:[],videomakers:[]});
  if(url.pathname==='/api/config/empresa')return reply({empresa:{nomeFantasia:'Estúdio de demonstração'}});
  if(url.pathname==='/api/editores')return reply({editores:[]});
  if(url.pathname==='/api/videomakers')return reply({videomakers:[]});
  if(url.pathname.includes('notificacoes'))return reply({notificacoes:[],naoLidas:0});
  if(url.pathname.includes('foco'))return reply({emFoco:null,sugeridas:[],totalAbertas:0,atrasadas:0});
  if(url.pathname.includes('organizacoes'))return reply({organizacoes:[]});
  return reply({});
 });
 await page.goto('http://127.0.0.1:3107/usuarios?visual=novo');
 const person=page.getByRole('button',{name:'Abrir pessoa: Rafael Lima'});await person.waitFor();
 await page.screenshot({path:output+'/people.png'});
 await person.focus();await page.keyboard.press('Enter');
 const panel=page.getByRole('complementary',{name:'Detalhes da pessoa'});await panel.waitFor();
 await panel.getByRole('button',{name:'Acessos',exact:true}).click();
 await panel.getByRole('button',{name:'Redefinir senha'}).waitFor();
 await panel.getByRole('button',{name:'Editar permissões'}).waitFor();
 await page.screenshot({path:output+'/person-access.png'});
 assert(await page.locator('main').evaluate(el=>parseFloat(getComputedStyle(el).paddingRight)>=400),'space for open person panel');
 await panel.getByRole('button',{name:'Redefinir senha'}).click();
 await page.getByPlaceholder('Repita a senha').waitFor();
 await page.getByRole('button',{name:'Cancelar',exact:true}).click();
 await panel.getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Equipes',exact:true}).click();
 await page.getByText('Equipe é a área',{exact:false}).waitFor();
 await page.getByRole('button',{name:'Perfis de acesso',exact:true}).click();
 await page.getByText('Administrador',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Pessoas',exact:true}).click();await person.waitFor();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'people page overflow');
 await page.screenshot({path:output+'/people-mobile.png'});
 await page.goto('http://127.0.0.1:3107/configuracoes?visual=novo');
 const nav=page.getByRole('navigation',{name:'Seções de configurações'});await nav.waitFor();
 await nav.getByRole('button',{name:'Dados da Empresa'}).click();
 await page.locator("input").filter({visible:true}).first().waitFor();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'settings page overflow');
 await page.screenshot({path:output+'/settings-mobile.png'});
 await page.setViewportSize({width:1440,height:960});
 await page.screenshot({path:output+'/settings.png'});
 role='solicitante';await page.goto('http://127.0.0.1:3107/configuracoes?visual=novo');
 await page.getByText('Acesso restrito',{exact:true}).waitFor();
 assert.deepEqual(errors,[]);assert.deepEqual(mutations,[]);
 console.log(JSON.stringify({ok:true,checks:['people keyboard opening','access actions retained','teams and profiles','mobile no overflow','settings tabs','reset password dialog','restricted settings role','panel layout space'],errors,mutations}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
