// Teste visual isolado: TODA API é interceptada. Nenhum banco ou envio real.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { SignJWT } = require('jose');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
 const browser = await chromium.launch({headless:true,channel:"chrome"});
 const context = await browser.newContext({viewport:{width:1440,height:960},reducedMotion:'reduce'});
 const token = await new SignJWT({id:'preview-user',sub:'preview-user',tipo:'admin',papel:'admin',organizacaoId:'preview-org',name:'Pessoa de teste'}).setProtectedHeader({alg:'HS256'}).setIssuedAt().setExpirationTime('1h').sign(new TextEncoder().encode('nuflow-local-preview-only-secret-2026'.slice(0,32)));
 await context.addCookies([{name:'authjs.session-token',value:token,url:'http://127.0.0.1:3107'}]);
 const page = await context.newPage(); let failJobs = false; let failOrder = false; let writes = 0; const errors=[];page.on('pageerror', e=>errors.push(e.message));
 const statuses=['aguardando_triagem','planejamento','editando','revisao_pendente','postagem_pendente','entregue_cliente'];
 const columns=['entrada','producao','edicao','aprovacao','para_postar','finalizado'];
 const demands=Array.from({length:12},(_,i)=>({id:`demo-${i}`,codigo:`DEMO-${100+i}`,titulo:['Filme de lançamento','Campanha de primavera','Entrevista institucional','Conteúdo para redes','Captação de produto','Vídeo aprovado'][i%6],departamento:'audiovisual',tipoVideo:'reels',prioridade:i===0?'alta':'normal',statusVisivel:columns[i%6],statusInterno:statuses[i%6],finalizadaEm:new Date().toISOString(),dataLimite:'2026-12-20',editor:{nome:'Editor de teste'},posicaoKanban:i}));
 await context.route('**/*', async route=>{
  const url=new URL(route.request().url());
  if(url.hostname!=='127.0.0.1') return route.abort();
  if(!url.pathname.startsWith('/api/')) return route.continue();
  if(url.pathname.endsWith('/posicao')) {
    writes++;
    return route.fulfill({status:failOrder?403:200,contentType:'application/json',body:JSON.stringify(failOrder?{error:'Sem permissão'}:{ok:true})});
  }
  let data={};
  if(url.pathname==='/api/auth/session') data={user:{id:'preview-user',name:'Pessoa de teste',tipo:'admin'},expires:'2099-01-01'};
  else if(url.pathname==='/api/me') data={id:'preview-user',nome:'Pessoa de teste',tipo:'admin',superAdmin:false,modulos:{growth:true,eventos:false,ideias:true,mensagens:false},membership:{areas:['growth'],organizacaoId:'preview-org'},permissoes:{}};
  else if(url.pathname==='/api/demandas' && url.searchParams.get('tipoVideo')==='cobertura_evento') {
   if(failJobs) return route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Falha simulada'})});
   data={demandas:demands.map(d=>({...d,tipoVideo:'cobertura_evento',statusInterno:d.id==='demo-0'?'aguardando_aprovacao_interna':d.statusInterno}))};
  }
  else if(url.pathname==='/api/demandas') data={demandas:demands.filter(d=>!url.searchParams.get('search')||d.titulo.toLowerCase().includes(url.searchParams.get('search').toLowerCase()))};
  else if(url.pathname.includes('videomakers'))data={videomakers:[]};
  else if(url.pathname.includes('editores'))data={editores:[]};
  else if(url.pathname.includes('responsaveis'))data={responsaveis:[]};
  else if(url.pathname.includes('produtos'))data={produtos:[]};
  else if(url.pathname.includes('linhas-projetos'))data={linhas:[]};
  else if(url.pathname.includes('parametros'))data={parametros:[]};
  else if(url.pathname.includes('organizacoes'))data={organizacoes:[]};
  else if(url.pathname.includes('notificacoes'))data={notificacoes:[],naoLidas:0};
  else if(url.pathname.includes('foco'))data={emFoco:null,sugeridas:[],totalAbertas:0,atrasadas:0};
  else if(url.pathname.includes('whatsapp'))data={connected:false};
  return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});
 });
 const output=process.env.QA_OUTPUT || '/tmp/nuflow-kanban-qa';fs.mkdirSync(output,{recursive:true});
 await page.goto('http://127.0.0.1:3107/demandas?visual=novo');
 await page.getByText('Seu flow, à vista.').waitFor({timeout:90000});
 await page.getByText('Filme de lançamento',{exact:true}).first().waitFor();
 await page.screenshot({path:`${output}/desktop.png`});
 const firstCard=page.locator('[data-rfd-draggable-id="demo-0"]');
 await firstCard.focus(); await page.keyboard.press('Space'); await page.keyboard.press('ArrowDown'); await page.keyboard.press('Space');
 await page.waitForFunction(() => !document.querySelector('[role="status"]')?.textContent?.includes('Salvando ordem'));
 await page.waitForTimeout(500);
 assert.ok(writes>0,'Reordenação por teclado deve persistir');
 failOrder=true;
 await firstCard.focus(); await page.keyboard.press('Space'); await page.keyboard.press('ArrowUp'); await page.keyboard.press('Space');
 await page.getByRole('button',{name:'Recarregar quadro para conferir'}).waitFor();
 await page.getByRole('button',{name:'Recarregar quadro para conferir'}).click(); failOrder=false;
 await page.getByText('Seu flow, à vista.').waitFor();
 await page.getByRole('button',{name:'Nova Demanda',exact:true}).click();
 await page.getByText('Título da demanda',{exact:false}).first().waitFor();
 await page.getByRole('dialog').waitFor();
 await page.getByRole('button',{name:'Fechar',exact:true}).focus();
 await page.keyboard.press('Shift+Tab');
 assert.ok(await page.getByRole('dialog').evaluate(el=>el.contains(document.activeElement)));
 await page.keyboard.press('Escape');
 await page.getByRole('dialog').waitFor({state:'hidden'});
 // Fecha a navegação/formulário sem escrita recarregando somente o ambiente simulado.
 await page.goto('http://127.0.0.1:3107/demandas?visual=novo');
 await page.getByText('Seu flow, à vista.').waitFor();
 assert.equal(await page.getByRole('button',{name:'Audiovisual',exact:true}).getAttribute('aria-expanded'),'true');
 await page.getByRole('button',{name:'Growth',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'Audiovisual',exact:true}).getAttribute('aria-expanded'),'false');
 await page.getByRole('button',{name:'Voltar ao clássico'}).click();
 await page.getByRole('button',{name:'Usar novo visual'}).first().waitFor();
 await page.getByRole('button',{name:'Usar novo visual'}).first().click();
 await page.goto('http://127.0.0.1:3107/design');
 await page.getByText('Seu flow, à vista.').waitFor();
 await page.screenshot({path:`${output}/growth.png`});
 await page.setViewportSize({width:390,height:844});
 await page.goto('http://127.0.0.1:3107/demandas');
 await page.getByText('Seu flow, à vista.').waitFor();
 await page.getByRole('button',{name:'Buscar e filtrar'}).click();
 await page.getByPlaceholder('Buscar demanda...').fill('Filme');
 await page.getByRole('button',{name:'Buscar e filtrar'}).click();
 await page.screenshot({path:`${output}/mobile.png`});
 const cardBox=await page.getByRole('link',{name:'Abrir demanda: Filme de lançamento'}).first().boundingBox();
 assert.ok(cardBox && cardBox.y < 844,'Card precisa aparecer na primeira tela mobile');
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 assert.equal(overflow,false,'Página não deve transbordar horizontalmente');
 await page.getByRole('button',{name:'Abrir navegação'}).click();
 await page.getByRole('button',{name:'Fechar navegação'}).waitFor({state:'visible'});
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Fechar navegação'}).waitFor({state:'hidden'});
 await page.setViewportSize({width:1440,height:960});
 await page.goto('http://127.0.0.1:3107/jobs?visual=novo');
 await page.getByRole('heading',{name:'Seu próximo job. À vista.'}).waitFor();
 await page.getByRole('button').filter({hasText:'DEMO-101'}).waitFor();
 assert.equal(await page.getByRole('button').filter({hasText:'DEMO-100'}).count(),0,'Solicitação pendente não deve entrar em Jobs');
 await page.screenshot({path:`${output}/jobs-desktop.png`});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:`${output}/jobs-mobile.png`});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.getByRole('button',{name:'Buscar e filtrar'}).click();
 await page.getByRole('textbox',{name:'Buscar jobs por código ou título'}).fill('Teste');
 await page.getByRole('button',{name:'Buscar e filtrar'}).click();
 failJobs=true;
 await page.goto('http://127.0.0.1:3107/jobs?visual=novo');
 await page.getByRole('button',{name:'Tentar novamente'}).waitFor();
 failJobs=false;
 await page.getByRole('button',{name:'Tentar novamente'}).click();
 await page.getByRole('button').filter({hasText:'DEMO-101'}).waitFor();
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({ok:true,checks:['Jobs desktop/mobile','Jobs exclui solicitação pendente','Jobs falha e retry','desktop','Growth','toggle clássico','persistência entre rotas','menu sanfona','mobile sem overflow','gaveta Escape','reordenação por teclado','erro HTTP 403','abertura de formulário','filtro mobile','card visível na primeira tela'],output}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
