require('dotenv').config({path:'.env.local',quiet:true});
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict');
const {PrismaClient}=require('@prisma/client'),{PrismaPg}=require('@prisma/adapter-pg');
const url=new URL(process.env.DATABASE_URL);assert(url.hostname==='127.0.0.1'&&url.port==='55437'&&url.pathname==='/nuflow_local');
const db=new PrismaClient({adapter:new PrismaPg({connectionString:url.toString()})});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),ctx=await browser.newContext({viewport:{width:1440,height:960}}),ids=[],errors=[];
await ctx.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));
try{const a=await db.organizacao.findUniqueOrThrow({where:{slug:'estudio-local-a'}}),b=await db.organizacao.findUniqueOrThrow({where:{slug:'estudio-local-b'}});
for(const [titulo,org,hours,status] of [['Hoje QA próximo',a.id,0.01,'agendado'],['Hoje QA externo',b.id,0.01,'agendado'],['Hoje QA futuro',a.id,240,'agendado'],['Hoje QA encerrado',a.id,-48,'concluido'],['Hoje QA cancelado',a.id,0.02,'cancelado']]){const e=await db.evento.create({data:{titulo,organizacaoId:org,inicio:new Date(Date.now()+hours*3600000),fim:new Date(Date.now()+(hours+1)*3600000),status,lembreteEnviado:true}});ids.push(e.id)}
await page.goto('http://127.0.0.1:3108/login');await page.locator('[name=login]').fill('admin-a@nuflow.test');await page.locator('[name=password]').fill('NuFlow-Local-2026!');await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.waitForURL('**/dashboard');await page.goto('http://127.0.0.1:3108/hoje?visual=novo');await page.getByRole('link',{name:/Hoje QA próximo/}).waitFor();for(const name of ['externo','futuro','encerrado','cancelado'])assert.equal(await page.getByRole('link',{name:new RegExp('Hoje QA '+name)}).count(),0);
assert((await page.getByRole('region',{name:'Trabalhos em andamento'}).locator('a[href^="/demandas/"]').count())<=3);
await page.screenshot({path:'/tmp/nuflow-today-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/nuflow-today-mobile.png',fullPage:true});await page.getByRole('region',{name:'Próximos compromissos'}).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/nuflow-today-agenda-mobile.png'});await page.getByRole('link',{name:'Ver meu trabalho →'}).click();await page.waitForURL('**/meu-trabalho');await page.getByRole('button',{name:'Minhas',exact:true}).waitFor();assert.deepEqual(errors,[]);console.log('PASS: Hoje, agenda por empresa/período/status, até 3 trabalhos, navegação, mobile sem overflow');
}finally{await db.evento.deleteMany({where:{id:{in:ids}}});await db.$disconnect();await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
